### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by y4nnick** [timonweb/manage.py-anywhere#1]
I get following Syntax Error when running manage.py:

```
File "manage.py", line 8
    while [[ "`pwd`" != '/' ]]; do
                              ^
SyntaxError: invalid syntax
```

Maschine: Ubuntu 14.04.2
Python: 2.7.6

**Comment by timonweb** [comment]
Hmm, tried to run it on Ubuntu 14.04.2 and all is fine on my side. Could you please tell in what directory you're trying to run this command, so I could try to replicate your conditions...

**Comment by y4nnick** [comment]
I am trying it in /usr/local/bin. My real manage.py file is in /vagrant_data/dev.
